### ISSUE TITLE
Starred notes

### ISSUE THREAD

**Issue by singaltanmay** [singaltanmay/flutter-notes#7]

**Comment by abhishek-jain-1999** [comment]
bhai phele decide kar le starred wala chahiye ki nhi 

last tune kha tha ki starr wala abhi aise hi liye main all notes wale se connect kara tha

**Comment by singaltanmay** [comment]
haan starred notes chahiye but uske page mein hum aur bhi notes mix kardenge jaise ki upvoted etc
